export const FETCH_RECIPES = 'FETCH_RECIPES';
export const SHOW_ERROR = 'SHOW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const OPEN_IMAGE_ZOOM_MODAL = 'OPEN_IMAGE_ZOOM_MODAL';
export const CLOSE_IMAGE_ZOOM_MODAL = 'CLOSE_IMAGE_ZOOM_MODAL';
export const SET_MODAL_RECIPE = 'SET_MODAL_RECIPE';
export const OPEN_ADD_RECIPE_MODAL = 'OPEN_ADD_RECIPE_MODAL';
export const CLOSE_ADD_RECIPE_MODAL = 'HIDE_ADD_RECIPE_MODAL';